name: Publish to NPM
on: [push]
permissions:
  id-token: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: cat ./package.json
      - uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
          major-wording: ''
          minor-wording: ''
          patch-wording: ''
          rc-wording: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ secrets.NAME }}
          GITHUB_EMAIL: ${{ secrets.EMAIL }}
      - run: cat ./package.json
      - run: NODE_AUTH_TOKEN="" npm publish
